### ISSUE TITLE
json example doesn't works - "Loading..." but no scripts displayed

### ISSUE THREAD

**Issue by brunetton** [NastuzziSamy/ulauncher-custom-scripts#10]
Using the extension with default json example file doesn't work: 

~/.config/ulauncher/scripts.json
```json
{
  "name": "Edit_scripts",
  "description": "Select to edit scripts",
  "icon": null,
  "script": "xdg-open",
  "default_arguments": [
    "~/.config/ulauncher/scripts.json"
  ]
}
```

In logs:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/api/client/Client.py", line 54, in on_message
    self.extension.trigger_event(event)
  File "/usr/lib/python3/dist-packages/ulauncher/api/client/Extension.py", line 52, in trigger_event
    action = listener.on_event(event, self)
  File "/home/bruno/.local/share/ulauncher/extensions/com.github.nastuzzisamy.ulauncher-custom-scripts/main.py", line 32, in on_event
    results, params = launcher.get_first_scripts()
  File "/home/bruno/.local/share/ulauncher/extensions/com.github.nastuzzisamy.ulauncher-custom-scripts/src/scripts.py", line 36, in get_first_scripts
    return self.config[:MAX_SCRIPTS], []
TypeError: unhashable type: 'slice'
```

## Solution

The json must be an **array**

**Comment by NastuzziSamy** [comment]
It is now fixed thanks to brunetton :)
